P8105 Homework 2
================
xj2357

# Problem 1

## Import the subway data

``` r
subway_df =
  read_csv("data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
  show_col_types = FALSE) |>
  janitor::clean_names() |>
  select(line, station_name, station_latitude, station_longitude,
  starts_with("route"), entry, vending, entrance_type, ada) |>
  mutate(entry = entry == "YES")

glimpse(subway_df)
```

    ## Rows: 1,868
    ## Columns: 19
    ## $ line              <chr> "4 Avenue", "4 Avenue", "4 Avenue", "4 Avenue", "4 A…
    ## $ station_name      <chr> "25th St", "25th St", "36th St", "36th St", "36th St…
    ## $ station_latitude  <dbl> 40.66040, 40.66040, 40.65514, 40.65514, 40.65514, 40…
    ## $ station_longitude <dbl> -73.99809, -73.99809, -74.00355, -74.00355, -74.0035…
    ## $ route1            <chr> "R", "R", "N", "N", "N", "R", "R", "R", "R", "R", "R…
    ## $ route2            <chr> NA, NA, "R", "R", "R", NA, NA, NA, NA, NA, NA, NA, N…
    ## $ route3            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
    ## $ route4            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
    ## $ route5            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
    ## $ route6            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
    ## $ route7            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
    ## $ route8            <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
    ## $ route9            <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
    ## $ route10           <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
    ## $ route11           <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
    ## $ entry             <lgl> TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE…
    ## $ vending           <chr> "YES", "YES", "YES", "YES", "YES", "YES", "YES", "YE…
    ## $ entrance_type     <chr> "Stair", "Stair", "Stair", "Stair", "Stair", "Stair"…
    ## $ ada               <lgl> FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FAL…

The cleaned dataset contains 1868 entrance/exit records and 19
variables. The variables describe the subway line, station name and
coordinates, routes served, entry permission, vending availability,
entrance type, and ADA compliance. I standardized the column names,
retained the requested variables, and converted entry from YES/NO to a
logical variable. The route information still needs tidying because it
is spread across route1 through route11 rather than stored in a single
route-name column.

## Station counts and entry access

``` r
n_stations =
  subway_df |>
  distinct(line, station_name) |>
  nrow()

n_ada_stations =
  subway_df |>
  filter(ada == TRUE) |>
  distinct(line, station_name) |>
  nrow()

entry_prop_no_vending =
  subway_df |>
  filter(vending == "NO") |>
  pull(entry) |>
  mean()
```

Stations are identified by the combination of line and station name.
There are 465 distinct stations, of which 84 are ADA compliant.

Among entrances/exits without vending, approximately 37.7% allow entry.

## Tidy the route information

``` r
subway_long_df =
  subway_df |>
  mutate(
    across(starts_with("route"), as.character)
  ) |>
  pivot_longer(
    cols = starts_with("route"),
    names_to = "route_number",
    names_prefix = "route",
    values_to = "route_name",
    values_drop_na = TRUE
  ) |>
  mutate(
    route_number = as.integer(route_number)
  )

n_a_stations =
  subway_long_df |>
  filter(route_name == "A") |>
  distinct(line, station_name) |>
  nrow()

n_a_ada_stations =
  subway_long_df |>
  filter(route_name == "A", ada == TRUE) |>
  distinct(line, station_name) |>
  nrow()
```

I converted the route columns to character variables and reshaped them
into route_number and route_name. Missing route entries were omitted.
Each row now represents one route served by an entrance/exit record. The
resulting dataset contains 4270 rows and 10 columns.

There are 60 distinct stations serving the A train, of which 17 are ADA
compliant.

# Problem 2

## Import and clean Mr. Trash Wheel data

``` r
mr_trash_df =
  readxl::read_excel(
    "data/trash_wheel_202610.xlsx",
    sheet = "Mr. Trash Wheel",
    range = readxl::cell_limits(
      c(2, 1),
      c(NA, 14)
    )
  ) |>
  janitor::clean_names() |>
  filter(!is.na(dumpster)) |>
  mutate(
    year = as.integer(year),
    date = as.Date(date),
    sports_balls = as.integer(round(sports_balls)),
    wheel = "Mr. Trash Wheel"
  )

glimpse(mr_trash_df)
```

    ## Rows: 740
    ## Columns: 15
    ## $ dumpster           <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, …
    ## $ month              <chr> "May", "May", "May", "May", "May", "May", "May", "M…
    ## $ year               <int> 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 201…
    ## $ date               <date> 2014-05-16, 2014-05-16, 2014-05-16, 2014-05-17, 20…
    ## $ weight_tons        <dbl> 4.31, 2.74, 3.45, 3.10, 4.06, 2.71, 1.91, 3.70, 2.5…
    ## $ volume_cubic_yards <dbl> 18, 13, 15, 15, 18, 13, 8, 16, 14, 18, 15, 19, 15, …
    ## $ plastic_bottles    <dbl> 1450, 1120, 2450, 2380, 980, 1430, 910, 3580, 2400,…
    ## $ polystyrene        <dbl> 1820, 1030, 3100, 2730, 870, 2140, 1090, 4310, 2790…
    ## $ cigarette_butts    <dbl> 126000, 91000, 105000, 100000, 120000, 90000, 56000…
    ## $ glass_bottles      <dbl> 72, 42, 50, 52, 72, 46, 32, 58, 49, 75, 38, 45, 58,…
    ## $ plastic_bags       <dbl> 584, 496, 1080, 896, 368, 672, 416, 1552, 984, 448,…
    ## $ wrappers           <dbl> 1162, 874, 2032, 1971, 753, 1144, 692, 3015, 1988, …
    ## $ sports_balls       <int> 7, 5, 6, 6, 7, 5, 3, 6, 6, 7, 6, 8, 6, 6, 6, 6, 5, …
    ## $ homes_powered      <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
    ## $ wheel              <chr> "Mr. Trash Wheel", "Mr. Trash Wheel", "Mr. Trash Wh…

## Import Professor Trash Wheel and Gwynnda

``` r
professor_df =
  readxl::read_excel(
    "data/trash_wheel_202610.xlsx",
    sheet = "Professor Trash Wheel",
    range = readxl::cell_limits(c(2, 1), c(NA, 13)),
    na = c("", "dive")
  ) |>
  janitor::clean_names() |>
  filter(!is.na(dumpster)) |>
  mutate(
    year = as.integer(year),
    date = as.Date(date),
    wheel = "Professor Trash Wheel"
  )

gwynnda_df =
  readxl::read_excel(
    "data/trash_wheel_202610.xlsx",
    sheet = "Gwynnda the Good Wheel of the W",
    range = readxl::cell_limits(c(2, 1), c(NA, 12))
  ) |>
  janitor::clean_names() |>
  filter(!is.na(dumpster)) |>
  mutate(
    year = as.integer(year),
    date = as.Date(date),
    wheel = "Gwynnda"
  )
```

The Professor Trash Wheel worksheet contains the nonnumeric text “dive”
in one plastic-bottle count cell. I treated this value as missing while
retaining the record and its other available measurements.

## Combine the three datasets

``` r
trash_df =
  bind_rows(mr_trash_df, professor_df, gwynnda_df)

count(trash_df, wheel)
```

    ## # A tibble: 3 × 2
    ##   wheel                     n
    ##   <chr>                 <int>
    ## 1 Gwynnda                 392
    ## 2 Mr. Trash Wheel         740
    ## 3 Professor Trash Wheel   137

``` r
dim(trash_df)
```

    ## [1] 1269   15

## Summary of the combined dataset

``` r
professor_total_weight =
  trash_df |>
  filter(wheel == "Professor Trash Wheel") |>
  pull(weight_tons) |>
  sum(na.rm = TRUE)

gwynnda_june_2022_butts =
  trash_df |>
  filter(
    wheel == "Gwynnda",
    year == 2022,
    month == "June"
  ) |>
  pull(cigarette_butts) |>
  sum(na.rm = TRUE)
```

The combined dataset contains 1269 dumpster collection records and 15
variables from three trash wheels. Key variables include collection
date, trash weight in tons, volume in cubic yards, and counts of items
such as plastic bottles and cigarette butts. The wheel variable
identifies the source of each record. I selected the relevant Excel
ranges, standardized column names and data types, removed rows without
dumpster numbers, and combined the three datasets. Sports-ball counts
were rounded and stored as integers. Variables absent from a source
worksheet are recorded as missing after combining.

Across the available records, Professor Trash Wheel collected 294.96
tons of trash. Gwynnda collected 18,120 cigarette butts in June 2022.

# Problem 3

## Import and clean the baseline data

``` r
baseline_raw =
  read_csv(
    "data/data_mci/MCI_baseline.csv",
    skip = 1,
    na = c("", "NA", "."),
    show_col_types = FALSE
  ) |>
  janitor::clean_names()

baseline_df =
  baseline_raw |>
  rename(baseline_age = current_age) |>
  mutate(
    sex = factor(
      sex,
      levels = c(0, 1),
      labels = c("Female", "Male")
    ),
    apoe4 = factor(
      apoe4,
      levels = c(0, 1),
      labels = c("Non-carrier", "Carrier")
    )
  ) |>
  filter(
    is.na(age_at_onset) | age_at_onset > baseline_age
  )

nrow(baseline_raw)
```

    ## [1] 483

``` r
nrow(baseline_df)
```

    ## [1] 479

``` r
glimpse(baseline_df)
```

    ## Rows: 479
    ## Columns: 6
    ## $ id           <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17…
    ## $ baseline_age <dbl> 63.1, 65.6, 62.5, 69.8, 66.0, 62.5, 66.5, 67.2, 66.7, 64.…
    ## $ sex          <fct> Female, Female, Male, Female, Male, Male, Male, Female, F…
    ## $ education    <dbl> 16, 20, 16, 16, 16, 16, 18, 18, 16, 18, 16, 18, 12, 20, 2…
    ## $ apoe4        <fct> Carrier, Carrier, Carrier, Non-carrier, Non-carrier, Non-…
    ## $ age_at_onset <dbl> NA, NA, 66.8, NA, 68.7, NA, 74.0, NA, NA, NA, NA, NA, 69.…

## Summarize the baseline data

``` r
n_mci =
  baseline_df |>
  filter(!is.na(age_at_onset)) |>
  nrow()

mean_baseline_age =
  baseline_df |>
  pull(baseline_age) |>
  mean()

women_apoe4_prop =
  baseline_df |>
  filter(sex == "Female") |>
  mutate(is_carrier = apoe4 == "Carrier") |>
  pull(is_carrier) |>
  mean()
```

I skipped the first row containing variable descriptions and treated “.”
as missing. I standardized column names, renamed current_age to
baseline_age, and converted sex and APOE4 carrier status to factors.
Participants whose MCI onset age was at or before their baseline age
were excluded. Missing onset ages were retained because they indicate
that participants remained MCI-free during follow-up.

The original baseline dataset contains 483 participants. After excluding
4 participants who already had MCI at baseline, 479 eligible
participants remain. The cleaned dataset has one row per participant and
6 variables: participant ID, baseline age, sex, years of education,
APOE4 carrier status, and age at MCI onset.

Among the eligible participants, 93 developed MCI during follow-up.
Their average baseline age was 65.03 years. Among women in this eligible
cohort, 30% were APOE4 carriers.

## Import and tidy the amyloid data

``` r
amyloid_wide_df =
  read_csv(
    "data/data_mci/mci_amyloid.csv",
    skip = 1,
    na = c("", "NA", "Na"),
    show_col_types = FALSE
  ) |>
  janitor::clean_names() |>
  rename(
    id = study_id,
    time_0 = baseline
  )

amyloid_df =
  amyloid_wide_df |>
  pivot_longer(
    cols = starts_with("time_"),
    names_to = "time",
    names_prefix = "time_",
    values_to = "amyloid_ratio",
    values_drop_na = FALSE
  ) |>
  mutate(time = as.integer(time)) |>
  arrange(id, time)

glimpse(amyloid_df)
```

    ## Rows: 2,435
    ## Columns: 3
    ## $ id            <dbl> 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4,…
    ## $ time          <int> 0, 2, 4, 6, 8, 0, 2, 4, 6, 8, 0, 2, 4, 6, 8, 0, 2, 4, 6,…
    ## $ amyloid_ratio <dbl> 0.1105487, NA, 0.1093252, 0.1047561, 0.1072577, 0.107481…

I skipped the first row containing descriptions and treated both “NA”
and “Na” as missing values. I standardized column names, renamed
study_id to id, and renamed the baseline measurement column to time_0.

I reshaped the five measurement columns into a numeric time variable and
an amyloid ratio variable. Time represents years since baseline, with
measurements scheduled at 0, 2, 4, 6, and 8 years. I retained missing
measurements and sorted the data by participant ID and time.

The amyloid dataset contains 487 participants. The tidy dataset has 2435
rows and 3 columns, with one row per participant and scheduled time
point. There are 172 missing amyloid values and 2263 observed values.

## Compare participant IDs

``` r
baseline_ids =
  baseline_df |>
  distinct(id)

amyloid_ids =
  amyloid_df |>
  distinct(id)

baseline_only =
  anti_join(baseline_ids, amyloid_ids, by = "id")

amyloid_only =
  anti_join(amyloid_ids, baseline_ids, by = "id")

amyloid_only_original =
  anti_join(amyloid_ids, baseline_raw, by = "id")

baseline_only
```

    ## # A tibble: 8 × 1
    ##      id
    ##   <dbl>
    ## 1    14
    ## 2    49
    ## 3    92
    ## 4   179
    ## 5   268
    ## 6   304
    ## 7   389
    ## 8   412

``` r
print(amyloid_only, n = Inf)
```

    ## # A tibble: 16 × 1
    ##       id
    ##    <dbl>
    ##  1    72
    ##  2   234
    ##  3   283
    ##  4   380
    ##  5   484
    ##  6   485
    ##  7   486
    ##  8   487
    ##  9   488
    ## 10   489
    ## 11   490
    ## 12   491
    ## 13   492
    ## 14   493
    ## 15   494
    ## 16   495

Comparing the cleaned datasets, 8 participants appear only in the
eligible baseline dataset, and 16 participants appear only in the
amyloid dataset.

Of those appearing only in the amyloid dataset, 12 are absent from the
original baseline file. The remaining 4 were present in the original
baseline file but were excluded because they already had MCI at
baseline.

## Combine and export the data

``` r
mci_df =
  inner_join(baseline_df, amyloid_df, by = "id") |>
  arrange(id, time)

dim(mci_df)
```

    ## [1] 2355    8

``` r
n_distinct(mci_df$id)
```

    ## [1] 471

``` r
write_csv(mci_df, "data/mci_combined.csv")
```

I joined the eligible baseline data to the longitudinal amyloid data by
participant ID, retaining only participants present in both datasets.

The combined dataset contains 471 participants, 2355 rows, and 8
columns. Each row represents one participant at one scheduled time
point. Baseline demographic information is repeated across that
participant’s five time points. The columns include ID, baseline age,
sex, education, APOE4 carrier status, age at MCI onset, time since
baseline, and amyloid ratio.

Missing amyloid measurements were retained; there are 167 missing
amyloid values in the combined dataset. I exported the resulting data to
data/mci_combined.csv.
